user:
  name:
    maximum: 50
  email:
    maximum: 50
  role:
    admin: "admin"
    normal: "normal"
languages:
  - "English"
  - "Japan"
page:
  max_page: 5
activities:
  create: "admin_create"
  update: "admin_update"
  destroy: "admin_destroy"
  days_of_week: 7
